#!/usr/bin/env python3

# This file is part of SunlightDPD - a home for open source software
# related to the dissipative particle dynamics (DPD) simulation
# method.

# Based on an original code copyright (c) 2007 Lucian Anton.
# Modifications copyright (c) 2008, 2009 Andrey Vlasov.  
# Additional modifications copyright (c) 2009-2016 Unilever UK Central
# Resources Ltd (Registered in England & Wales, Company No 29140;
# Registered Office: Unilever House, Blackfriars, London, EC4P 4BQ,
# UK).

# SunlightDPD is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# SunlightDPD is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with SunlightDPD.  If not, see <http://www.gnu.org/licenses/>.

# The results can be directly compared with Fig 5 of Wijmans et al
# [J. Chem. Phys. v114, 7644 (2001)].  The chemical potential
# difference muex_1 - muex_0 is exactly equal to the free energy
# change to convert a particle of species 0 into a particle of species
# 1.  Note that the calculation is done as a two component problem
# with a mole fraction of the second species set to zero.

# Here is the data from Fig 5 of Wijmans et al.  

#          dA dF

data1 = [[ 0, 0],
         [ 2, 0.699745],
         [ 4, 1.370293],
         [ 6, 2.0262583],
         [ 8, 2.6384122],
         [10, 3.2359834],
         [12, 3.7897591],
         [14, 4.3435348],
         [16, 4.853515],
         [18, 5.3488966],
         [20, 5.8296797],
         [22, 6.2812658],
         [24, 6.7182534],
         [26, 7.1406424],
         [28, 7.5338344],
         [30, 7.9270106]]

wsgx = list(data1[i][0] for i in range(len(data1)))
wsgy = list(data1[i][1] for i in range(len(data1)))

# Here is another set of data generated by accurate Monte-Carlo
# calculations of the chemical potential difference, using trial
# particle identity swaps.

#    dA   d(mu)   std-err

data2 = [[ 5,  1.702,  0.005],
         [10,  3.22,   0.01],
         [15,  4.56,   0.02],
         [20,  5.77,   0.02],
         [25,  6.85,   0.03]]

mcx = list(data2[i][0] for i in range(len(data2)))
mcy = list(data2[i][1] for i in range(len(data2)))
mce = list(data2[i][2] for i in range(len(data2)))

from oz import wizard as w

w.ncomp = 2
w.initialise()

rho = 3.0
A = 25.0
Amax = 55.0

w.arep[0,0] = w.arep[1,1] = A
w.rho[0] = rho
w.rho[1] = 0.0

npt = 41

x = []
y = []

for i in range(npt):
    dA = (Amax - A) * i / (npt - 1.0)
    w.arep[0,1] = A + dA
    w.dpd_potential()
    w.hnc_solve()
    x.append(dA)
    y.append(w.muex[1]-w.muex[0])
    print("%f\t%f\t%g" % (dA, w.muex[1]-w.muex[0], w.error))

import matplotlib.pyplot as plt

# plt.errorbar(mcx, mcy, yerr=mce, fmt='co', label='Monte-Carlo')
# error bars are smaller than symbols so just plot data

plt.plot(wsgx, wsgy, 'ro', label='Wijmans et al (2001)')
plt.plot(mcx, mcy, 'co', label='Monte-Carlo')
plt.plot(x, y, label='HNC')
plt.xlabel('$\\Delta A$')
plt.ylabel('$\\Delta F$')
plt.legend(loc='lower right')

plt.show()
